apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata: 
  name: demo-cluster
  region: us-east-2

nodeGroups:
  - name: ng1
    instanceType: t3.small
    desiredCapacity: 2


#eksctl create cluster -f cluster.yaml
